# Generated by Django 4.1.7 on 2023-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_number", models.CharField(max_length=50, unique=True)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("slots", models.IntegerField()),
            ],
        ),
    ]
