# Generated by Django 4.1.7 on 2023-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apmsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingslot",
            name="slots",
            field=models.IntegerField(null=True),
        ),
    ]
