# Generated by Django 4.1.7 on 2023-02-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apmsapp", "0003_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingslot",
            name="booked_by",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
