# Generated by Django 4.1.7 on 2023-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apmsapp", "0004_parkingslot_booked_by_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("direction", models.CharField(max_length=50, null=True)),
                ("images", models.CharField(max_length=100, null=True)),
                ("plateimages", models.CharField(max_length=100, null=True)),
                ("plateresult", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "t_users",
            },
        ),
        migrations.RemoveField(
            model_name="parkingslot",
            name="slot_type",
        ),
    ]
