# Generated by Django 4.1.7 on 2023-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apmsapp", "0005_user_remove_parkingslot_slot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingslot",
            name="license_plate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
