# Generated by Django 4.1.7 on 2023-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apmsapp", "0007_remove_parkingslot_license_plate_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingslot",
            name="slots",
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="license_plate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
